version: '3.8'

services:
  backend:
    build:
      context: ./tickets-backend
    ports:
      - "5000:5000"
    volumes:
      - ./tickets-backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://dhruvkulshrestha11:vrindaDhruv%4012@growthx.eptvn.mongodb.net/Tickets
      - PORT=5000
      - SECRET_KEY=ABCDEFG
    command: npm run dev
    networks:
      - ticketwise-network

  frontend:
    build:
      context: ./tickets-front
    ports:
      - "3000:3000"
    volumes:
      - ./tickets-front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URI=http://localhost:5000
    command: npm start
    networks:
      - ticketwise-network

networks:
  ticketwise-network:
    driver: bridge
